language: node_js

node_js:
  - 8
  - 7

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn run build
  - yarn run lint

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
